django/helloworld/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

django/task/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.details, name='details'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/request/', views.login_request_view, name='login-request'),
    path('login/resolve/', views.login_resolve_view, name='login-resolve'),
    path('add_task/', views.add_task, name='add-task'),
]

django/helloworld/models.py
from django.db import models

# Create your models here.

django/task/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.duration import duration_string
from django.utils.timesince import timeuntil

class TaskUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_master = models.BooleanField(default=False)

    @classmethod
    def from_user(cls, user):
        if user.is_anonymous:
            return None
        return cls.objects.filter(user=user).first()

class Task(models.Model):
    title = models.CharField(max_length=255)
    value = models.IntegerField()
    estimated_hours = models.IntegerField()
    deadline = models.DateTimeField()
    author = models.ForeignKey(TaskUser, on_delete=models.CASCADE)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'author={self.author.user.username} title="{self.title}"'

class OTP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    expired = models.BooleanField()

    @classmethod
    def get_valids(cls, user):
        return cls.objects.filter(
            user=user,
            expired=False,
            created_at__gte=timezone.now() - timedelta(hours=24)
        )

django/task/forms.py
from datetime import timedelta

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Task

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ('created_at', 'author')

    def clean_value(self):
        estimated = self.cleaned_data.get('estimated_hours')
        value = self.cleaned_data.get('value')
        if estimated is not None and value is not None and estimated < 72 and value > 50:
            self.add_error('value', 'maximum values for less than 3 days is 50$')
        return value

    def clean_deadline(self):
        now = timezone.now()
        deadline = self.cleaned_data.get('deadline')
        estimated = self.cleaned_data.get('estimated_hours')
        if estimated is None or deadline is None:
            return deadline
        if deadline < now + timedelta(hours=estimated):
            self.add_error('deadline', 'deadline and estimated hours doesnt match')
        return deadline

class LoginRequestForm(forms.Form):
    email = forms.EmailField()

class LoginResolveForm(forms.Form):
    password = forms.CharField(min_length=10, max_length=10)

class SignupForm(forms.Form):
    firstname = forms.CharField(max_length=100, strip=True)
    lastname = forms.CharField(max_length=100, strip=True)
    is_master = forms.BooleanField(required=False)

django/helloworld/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def index(request: HttpRequest):
    return HttpResponse(str(request.headers))

django/task/views.py
import logging
from datetime import timedelta

from django.contrib.auth import login, logout
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .forms import AddTaskForm, LoginRequestForm, LoginResolveForm, SignupForm
from .models import OTP, Task, TaskUser, User
from .decorators import (
    require_GET, require_POST,
    require_http_methods,
    require_full_signup_or_none,
    require_incomplete_signup,
    require_is_master,
    require_not_authenticated
)

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

def send_otp(email):
    user = User.objects.filter(username=email).first()
    if user is None:
        user = User.objects.create_user(username=email, email=email)
    otp = OTP.get_valids(user).first()
    if otp is None:
        otp = OTP.objects.create(
            user=user,
            password=User.objects.make_random_password(),
            expired=False
        )
    logger.info('send otp [user=%s, otp=%s]', user.username, otp.password)

@require_GET
@require_full_signup_or_none
def index(request):
    context = {
        'error': request.session.pop('error', None),
        'success': request.session.pop('success', None)
    }
    tasks = (
        Task.objects
        .select_related()
        .filter(deadline__gte=timezone.now())
        .order_by('deadline')
    )
    pagniator = Paginator(tasks, 10)
    page_num = request.GET.get('page') or request.session.get('page_num', 1)
    request.session['page_num'] = page_num
    context['page'] = pagniator.get_page(page_num)

    return render(request, 'task/index.html', context)

@require_GET
@require_full_signup_or_none
def details(request, task_id):
    context = {}
    context['task'] = get_object_or_404(Task, pk=task_id)
    taskuser = TaskUser.from_user(request.user)
    context['can_do'] = taskuser is not None and not taskuser.is_master
    return render(request, 'task/details.html', context)

@require_POST
@require_not_authenticated
def login_request_view(request):
    form = LoginRequestForm(request.POST)
    if not form.is_valid():
        request.session['error'] = form.errors.as_ul()
        return redirect('task:index')
    email = form.cleaned_data['email']
    send_otp(email)
    request.session['success'] = 'ایمیل ورود ارسال شد'
    return redirect('task:index')

@require_POST
@require_not_authenticated
def login_resolve_view(request):
    form = LoginResolveForm(request.POST)
    if not form.is_valid():
        request.session['error'] = form.errors.as_ul()
        return redirect('task:index')
    password = form.cleaned_data['password']
    otp = OTP.objects.filter(password=password).first()
    if otp is None:
        logger.warning('no such otp [otp=%s]', password)
        request.session['error'] = 'لینک ورود اشتباه است'
        return redirect('task:index')
    valid_otps = OTP.get_valids(otp.user)
    if otp not in valid_otps:
        logger.warning('not a valid otp [otp=%s]', otp.password)
        request.session['error'] = 'لینک ورود منقضی شده است'
        return redirect('task:index')
    valid_otps.update(expired=True)
    login(request, otp.user)
    if TaskUser.from_user(otp.user) is not None:
        request.session['success'] = 'با موفقیت وارد شدید'
        return redirect('task:index')
    return render(request, 'task/signup.html')

@require_http_methods(['GET', 'POST'])
@require_incomplete_signup
def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if not form.is_valid():
            context = {
                'error': form.errors.as_ul(),
                'form': form
            }
            return render(request, 'task/signup.html', context=context)
        cleaned_data = form.cleaned_data
        user = request.user
        user.first_name = cleaned_data['firstname']
        user.last_name = cleaned_data['lastname']
        user.save()
        taskuser = TaskUser.objects.create(
            user=user, is_master=cleaned_data['is_master']
        )
        request.session['success'] = 'اطلاعات با موفقیت ثبت شد'
        return redirect('task:index')
    return render(request, 'task/signup.html')

@require_POST
def logout_view(request):
    logout(request)
    request.session['success'] = 'با موفقیت خارج شدید'
    return redirect('task:index')

@require_http_methods(['GET', 'POST'])
@require_full_signup_or_none
@require_is_master
def add_task(request):
    context = {}
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = TaskUser.from_user(request.user)
            task.save()
            return redirect('task:details', task_id=task.pk)
        context['form'] = form
    return render(request, 'task/add_task.html', context)

django/task/templates/task/add_task.html
{% extends 'task/base.html' %}

{% block content %}
<style>
  #addTaskForm label {
    width: 110px;
  }
</style>
<div class="row">
  <div class="col-lg-6 mx-auto">
    <h3 class="mb-4">افزودن کار</h3>
    <form action="{% url 'task:add-task' %}" method="post" id="addTaskForm">
      {% csrf_token %}
      <div class="mb-3 input-group has-validation">
        <label for="id_title" class="input-group-text">عنوان</label>
        <input
          type="text"
          class="form-control {% if form.title.errors %}is-invalid{% elif form %}is-valid{% endif %}"
          name="title"
          id="id_title"
          maxlength="100"
          {% if form.title.value %}value="{{ form.title.value|escape }}"{% endif %}>
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
            <div>{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
      <div class="mb-3 input-group has-validation">
        <label for="id_deadline" class="input-group-text">ددلاین</label>
        <input
          type="text"
          name="deadline"
          id="id_deadline"
          class="form-control {% if form.deadline.errors %}is-invalid{% elif form %}is-valid{% endif %}"
          {% if form.deadline.value %}value="{{ form.deadline.value|escape }}"{% endif %}>
        <div class="invalid-feedback">
          {% for error in form.deadline.errors %}
            <div>{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
      <div class="mb-3 input-group has-validation">
        <label for="id_estimated_hours" class="input-group-text">تخمین زمانی</label>
        <input
          type="text"
          class="form-control {% if form.estimated_hours.errors %}is-invalid{% elif form %}is-valid{% endif %}"
          name="estimated_hours"
          id="id_estimated_hours"
          {% if form.estimated_hours.value %}value="{{ form.estimated_hours.value|escape }}"{% endif %}>
        <span class="input-group-text">ساعت</span>
        <div class="invalid-feedback">
          {% for error in form.estimated_hours.errors %}
            <div>{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
      <div class="mb-3 input-group has-validation">
        <label for="id_value" class="input-group-text">ارزش</label>
        <input
          type="text"
          class="form-control {% if form.value.errors %}is-invalid{% elif form %}is-valid{% endif %}"
          name="value"
          id="id_value"
          {% if form.value.value %}value="{{ form.value.value|escape }}"{% endif %}>
        <span class="input-group-text">$</span>
        <div class="invalid-feedback">
          {% for error in form.value.errors %}
            <div>{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
      <div class="mb-3 input-group has-validation">
        <label for="id_description" class="input-group-text">توضیحات</label>
        <textarea
          id="id_description"
          name="description"
          class="form-control {% if form.description.errors %}is-invalid{% elif form %}is-valid{% endif %}"
          form="addTaskForm">{% if form.description.value %}{{ form.description.value|escape }}{% endif %}</textarea>
        <div class="invalid-feedback">
          {% for error in form.description.errors %}
            <div>{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary w-100">اضافه کن</button>
    </form>
  </div>
</div>
{% endblock content %}

django/task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css" integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'task/style.css' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-dark bg-dark row">
      <div class="container-fluid">
        <a href="{% url 'task:index' %}" class="navbar-brand">سامانه انجام کار</a>
      </div>
    </nav>
    <div class="row">
      <div id="main-content" class="col-lg-9 mt-3">
        {% block content %}{% endblock %}
      </div>
      <div class="col-lg-3 mt-3" id="authentication">
        {% if error %}
          <div class="alert alert-danger" role="alert">{{ error|safe }}</div>
        {% endif %}
        {% if success %}
          <div class="alert alert-success" role="alert">{{ success|safe }}</div>
        {% endif %}
        {% if user.is_authenticated %}
          <h5>
            کاربر
            {{ user.get_full_name }} ({{ user.username }})
          </h5>
          {% if user.taskuser %}
            <div class="mb-3">
              به عنوان
              {% if user.taskuser.is_master %}
                کارفرما
              {% else %}
                پیمان‌کار
              {% endif %}
              وارد شده‌اید.
            </div>
          {% else %}
            <div class="alert alert-warning" role="alert">اطلاعات حساب کاربری خود را تکمیل کنید</div>
          {% endif %}
          {% if user.taskuser.is_master  %}
            <a href="{% url 'task:add-task' %}" class="btn btn-dark w-100 mb-2">افزودن کار</a>
          {% endif %}
          <form action="{% url 'task:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark w-100">خروج</button>
          </form>
        {% else %}
          <h3 class="mb-4"> ورود </h3>
          <form action="{% url 'task:login-request' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <input type="email" class="form-control" name="email" placeholder="ایمیل">
            </div>
            <button type="submit" class="btn btn-dark w-100">ورود</button>
          </form>
          <hr>
          <h3 class="mt-5 mb-3">ورود با رمز یکبار مصرف</h3>
          <form action="{% url 'task:login-resolve' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <input type="password" class="form-control" name="password" placeholder="رمز یکبار مصرف">
            </div>
            <button type="submit" class="btn btn-dark w-100">ورود</button>
          </form>
        {% endif %}
        <hr>
      </div>
    </div>
    <footer>
      <hr>
      <span> درباره‌ی ما</span>
      <span>قوانین</span>
    </footer>
  </div>
</body>
</html>

django/task/templates/task/details.html
{% extends 'task/base.html' %}
{% load cache %}
{% block content %}
<div class="row mt-3">
  <div class="col-sm-12 d-flex flex-row">
    <h3 class="flex-grow-1">{{ task.title }}</h3>
    <a class="btn btn-primary px-5{% if not can_do %} disabled{% endif %}">انجام می‌دم</a>
  </div>
</div>
<hr>
{% cache 300 task_details task.id %}
<div class="row mt-3">
  <div class="col-sm-2">
    {{ task.author.user.get_full_name }}
  </div>
  <div class="col-sm-4">
    ساخته شده در
    <span>{{ task.created_at|date:"Y/n/j G:i"}}</span>
  </div>
  <div class="col-sm-3">{{ task.value }}$</div>
  <div class="col-sm-3">{{ task.estimated_hours }} ساعت</div>
</div>
<div class="row mt-3">
  <div class="col-sm-12">
    <h3>توضیحات</h3>
    <p>{{ task.description }}</p>
  </div>
</div>
{% endcache %}
{% endblock content %}

django/task/templates/task/index.html
{% extends 'task/base.html' %}
{% load cache %}
{% block content %}
{% cache 300 task_index page.number %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>عنوان کار</th>
      <th>ارزش کار</th>
      <th>تخمین زمانی</th>
      <th>صاحب کار</th>
      <th>توضیحات</th>
    </tr>
  </thead>
  <tbody>
    {% for task in page %}
      <tr>
        <td>{{ task.title }}</td>
        <td>{{ task.value }}$</td>
        <td>{{ task.estimated_hours }} ساعت</td>
        <td>{{ task.author.user.get_full_name }}</td>
        <td>
          <a href="{% url 'task:details' task.id %}" class="btn btn-primary">توضیحات بیشتر</a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<div id="tasks-paginator">
  <nav>
    <ul class="pagination justify-content-center">
      {% if not page.has_previous %}
        <li class="page-item disabled">
          <span class="page-link">&laquo;</span>
        </li>
        <li class="page-item disabled">
          <span class="page-link">قبلی</span>
        </li>
      {% else %}
        <li class="page-item">
          <a href="?page=1" class="page-link">&laquo;</a>
        </li>
        <li class="page-item">
          <a href="?page={{ page.previous_page_number }}" class="page-link">قبلی</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a href="?page={{ page.number }}" class="page-link">{{ page.number }}</a>
      </li>
      {% if not page.has_next %}
        <li class="page-item disabled">
          <span class="page-link">بعدی</span>
        </li>
        <li class="page-item disabled">
          <span class="page-link">&raquo;</span>
        </li>
      {% else %}
        <li class="page-item">
          <a href="?page={{ page.next_page_number }}" class="page-link">بعدی</a>
        </li>
        <li class="page-item">
          <a href="?page={{ page.paginator.num_pages }}" class="page-link">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endcache %}
{% endblock content %}

django/task/templates/task/signup.html
{% extends 'task/base.html' %}

{% block content %}
<div class="row">
  <div class="col-lg-6 mx-auto">
    <h3 class="mb-4">ثبت نام</h3>
    <form action="{% url 'task:signup' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <input
          class="form-control"
          type="text"
          name="firstname"
          id="firstname"
          placeholder="نام"
          value="{{ form.firstname.value }}">
      </div>
      <div class="mb-3">
        <input
          class="form-control"
          type="text"
          name="lastname"
          id="lastname"
          placeholder="نام خانوادگی"
          value="{{ form.lastname.value }}">
      </div>
      <div class="mb-3 form-check">
        <input
          name="is_master"
          type="checkbox"
          class="form-check-input">
        <label class="form-check-label" for="master">کارفرما</label>
      </div>
      <button type="submit" class="btn btn-primary w-100" value="login">ثبت نام</button>
    </form>
  </div>
</div>
{% endblock content %}